apiVersion: v1
kind: ConfigMap
metadata:
  name: udagram-api-feed-configmap
  namespace: udagram
  labels:
    app: udagram-api-feed
data:
  APP_NAME: udagram-feed-api
  NODE_ENV: production
  PORT: "8080"
  USER_SERVICE: http://udagram-api-user:8080
  AWS_REGION: us-east-1
  AWS_BUCKET: jandir-nanodegree-udagram
  AWS_SQS_QUEUE_URL: https://sqs.us-east-1.amazonaws.com/186158723311/feed-user-events
  JWT_SECRET_NAME: prod/jwt/keys
  API_KEYS_NAME: prod/api/keys
