apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend
  namespace: udagram
  labels:
    app: udagram-frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  selector:
    app: udagram-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
