apiVersion: v1
kind: Service
metadata:
  name: udagram-api-user
  labels:
    app: udagram-api-user
spec:
  selector:
    app: udagram-api-user
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
