apiVersion: v1
kind: Service
metadata:
  name: udagram-api-feed
  namespace: udagram
  labels:
    app: udagram-api-feed
spec:
  selector:
    app: udagram-api-feed
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
