apiVersion: v1
kind: Service
metadata:
  name: udagram-reverseproxy
  namespace: udagram
  labels:
    app: udagram-reverseproxy
spec:
  selector:
    app: udagram-reverseproxy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
