apiVersion: v1
kind: ConfigMap
metadata:
  name: udagram-frontend-configmap
  namespace: udagram
  labels:
    app: udagram
data:
  # The frontend is static, so environment variables are usually injected at build time.
  # This ConfigMap can be used for custom Nginx configurations if needed in the future.
  APP_NAME: udagram-frontend
  NODE_ENV: production
  VITE_API_URL: http://udagramapi.jandir.site
